PACKAGE_NAME="d330-i915"
PACKAGE_VERSION="2.0"

BUILT_MODULE_NAME[0]="i915"
BUILT_MODULE_LOCATION[0]="drivers/gpu/drm/i915"
DEST_MODULE_LOCATION[0]="/updates/dkms"

PRE_BUILD="./dkms-prebuild.sh ${kernel_source_dir}"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/drivers/gpu/drm/i915 modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/drivers/gpu/drm/i915 clean"

AUTOINSTALL="yes"
